### ISSUE TITLE
How is order determined?

### ISSUE THREAD

**Issue by waynebeaton** [ShaneCurcuru/chooseafoundation#9]
At my current resolution, I can't see Eclipse Foundation without scrolling.
How do you determine order? If the order is random, then it should always be random. in its current form, the order in which the foundations are listed implies bias.

**Comment by ShaneCurcuru** [comment]
Order is currently fixed based on my rough perception of project interest in the larger ecosystem.  

It should be changed to be random.  Patches welcome that work when hosted on gh-pages.  Otherwise I have it on my list to find some simple JavaScript that intelligently randomizes for browsers that support JavaScript (with the "Get More Help" link always being last).

I'm also open to CSS/style improvements to the homepage that better size the blocks so that the second row would always be visible (at least partially) on common desktop screens.

**Comment by waynebeaton** [comment]
Your perception is biased (as is my own).
In the absence of being able to randomise, listing alphabetically seems like a reasonably unbiased way of presenting the list of foundations.

**Comment by apetro** [comment]
Suggestion: 

Embrace bias, acknowledge it, and put it to work for good. Not all foundations are of equal likely interest. [choosealicense.com does not equally emphasize all licenses](https://choosealicense.com/) -- it highlights three that it seems will meet most needs. **There's value in curation. There are probably a few foundations that have the interest, capacity, wide applicability such that they're right for consideration by many projects**, analogously to the situation with open source licenses. I think chooseafoundation will be a stronger site if it acknowledges this reality, tries to provide plausible initial guidance to projects, and also acknowledges the complexity of the options and the long tail of open source foundations in the world. Shane, your "rough perception of project interest in the larger ecosystem" is worth hearing, presented carefully and acknowledging there's more to explore and consider.

**Comment by ShaneCurcuru** [comment]
The focus is on open source communities of individuals managing projects who may want to find an organization to host them - or, to give them enough pointers (coming) to send them to the right advice for incorporating themselves.  A secondary focus is on individual maintainers of popular open source projects who want to build an independent community.  I am not (particularly) focusing on medium or large-scale corporate projects because they typically have their own resources and motivations for finding external governance and corporate shields. (Which reminds me: an area to add is legal protections for committers/project maintainers.)

In terms of curating:
- Organizations must promote use of OSI-approved licenses for their hosted projects, and the focus is on some sort of openly developed/governed projects, not closed or commercial projects; and 
- Orgs must be actively and visibly accepting new hosted projects to be on the front page.
- Orgs must not be tied to a single vendor (i.e. not only accepting projects from or related to a single outside company).
- Higher weighting for being on the homepage and/or being on the first "row" tends to include:
-- Stable organizations that are known in the ecosystem with a track record.
-- Sufficient hosted projects to show that they are focused on providing services to any suitable project that wants to join (modulo their own general guidelines).
-- Orgs interested in hosting a broad range of projects and communities.
-- Orgs that allow hosted communities some independence in their governance.

Note that "hosted projects" means independent communities with their own brand, governance (of some level), software product, repository, and communication mechanisms.  In particular, "hosted projects" means what the ASF considers Top Level Projects - ones that the ASF formally recognizes and provides full services for.  Projects in states similar to the Apache Incubator (proposing to join, working towards graduation as mature community) and the Apache Attic (code, but no active governance or future releases planned) are not counted in totals currently.  If there's sufficient interest, I might include an "Other projects" total in the future, but I don't think that's as relevant.

**Comment by ShaneCurcuru** [comment]
I would certainly accept a patch to randomize the first four entries - SPI really isn't as big in a public awareness way as the others. But haven't had time to do real coding myself yet.

**Comment by ShaneCurcuru** [comment]
See #13 for future work.  Should be a weighted randomization, with ASF, LF, Eclipse (I think) as double weights compared to rest given their size/regular addition of new project communities.
